export const GET_USER ='GET_USER';
export const USER_ERROR = 'USER_ERROR';
export const GET_USER_OTP ='GET_USER_OTP';
export const GET_QR_CODE = 'GET_QR_CODE';
export const GET_VHEICLE_DETAILS='GET_VHEICLE_DETAILS';
export const GET_IOT_TOKEN = 'GET_IOT_TOKEN';
export const GET_AUTH_TOKAN= 'GET_AUTH_TOKAN';
export const GET_COORDINATE = 'GET_COORDINATE';
export const POST_DEALER_DATA_COORDINATES = "POST_DEALER_DATA_COORDINATES"

export const SAVE_CORDINATE_DATA = "SAVE_CORDINATE_DATA"

export const SAVE_CURRENT_COORDINATES = "SAVE_CURRENT_COORDINATES"